services:
  caddy:
    image: caddy:2.8
    user: "444:444"
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    cap_add:
      - NET_ADMIN
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - ./Caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./Caddy/config:/config
      - ./Caddy/data:/data
      - ./public:/public:ro
      - ./logs:/logs
  carddealer:
    build:
      context: ./CardDealer
      args:
        - UNPRIV_UID_GID=444
    restart: always
    env_file: credentials
    depends_on:
      caddy:
        condition: service_started
    environment:
      - PYTHONUNBUFFERED=1 # flush logs immediately 
      - TZ=America/Sao_Paulo # log dates in my timezone
    volumes:
      - ./entered_channels.txt:/app/entered_channels.txt
      - ./public/cards/:/var/www/html/cards/
      - ./logs:/app/logs
  watchdog:
    build:
      context: ./Watchdog
      args:
        - UNPRIV_UID_GID=444
    restart: always
    env_file: credentials
    depends_on:
      carddealer:
        condition: service_started
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=America/Sao_Paulo
    volumes:
      - ./last_heartbeat:/app/last_heartbeat
