version: 1
disable_existing_loggers: false
formatters:
  myformatter:
    format: '%(asctime)s,%(levelname)s,%(message)s'
    datefmt: '%Y-%m-%dT%H:%M:%S%z'
handlers:
  root_handler:
    class: logging.handlers.RotatingFileHandler
    formatter: myformatter
    filename: logs/debug.log
    maxBytes: 10000000
    backupCount: 3
  microbebingo_handler:
    class: logging.handlers.RotatingFileHandler
    formatter: myformatter
    filename: logs/microbebingo.log
    maxBytes: 10000000
    backupCount: 3
loggers:
  root:
    level: DEBUG
    handlers:
    - root_handler
  microbebingo:
    level: INFO
    handlers:
    - microbebingo_handler
